### ISSUE TITLE
Page number missing fluent treatment

### ISSUE THREAD

**Issue by edge261** [tobyisawesome/bing-fluent-skin#1]
As the title mentions, the page number does not have the rounded corners.
<img width="931" alt="image" src="https://github.com/tobyisawesome/bing-fluent-skin/assets/79731301/1c04c66b-697f-4285-b4d0-ce55a72981bd">

**Comment by tobyisawesome** [comment]
Noted - it will likely look like this next update 👍
![image](https://github.com/tobyisawesome/bing-fluent-skin/assets/71511385/118fb29a-46e4-4753-b805-da4df5fbe7bf)
Code:
```
#b_results>.b_pag .sb_pagS_bp {
    color: #fff;
    background: #174ae4 !important;
    border-radius: 999px;
}
.b_pag a.sb_bp {
    min-width: 40px;
    margin-right: 20px;
    line-height: 37px;
}
body, .b_promoteText, #b_tween a.ftrH:hover, .b_expando, .b_expando h2, .b_active a, .b_active a:visited, .b_active a:hover, #b_results>.b_pag a, #b_results .b_no, #b_content a.cbl:visited, #b_content a.cbl {
    color: #71777d;
    border-radius: 999px;
}
```

**Comment by tobyisawesome** [comment]
Complete in latest version
