### ISSUE TITLE
Bing dark mode is broken

### ISSUE THREAD

**Issue by foursplaysroblox** [tobyisawesome/bing-fluent-skin#10]
![image](https://github.com/tobyisawesome/bing-fluent-skin/assets/82078139/942d68cd-312a-4c30-9b09-f16753434685)
![image](https://github.com/tobyisawesome/bing-fluent-skin/assets/82078139/3e833dd8-820d-476b-bfc1-56af79f56d3c)

**Comment by tobyisawesome** [comment]
Please use the Fluent Bing dark theme instead.
https://userstyles.world/style/10917/fluent-bing-dark
