### ISSUE TITLE
Bing background does not show in dark mode

### ISSUE THREAD

**Issue by foursplaysroblox** [tobyisawesome/bing-fluent-skin#11]
![image](https://github.com/tobyisawesome/bing-fluent-skin/assets/82078139/3f7e38e2-c9b0-4dac-9346-5c054afe0ce0)

**Comment by tobyisawesome** [comment]
Intentional, "New Bing" Background Dark does not exist yet. The New Bing Background skin should only be used with the Light version of Fluent Bing. Other enhancements that come along with the New Bing Background such as consistent backgrounds for widgets are already implemented in Bing Fluent Dark.

**Comment by foursplaysroblox** [comment]
ok
