### ISSUE TITLE
UI Issues with background enabled

### ISSUE THREAD

**Issue by smcmackin20** [tobyisawesome/bing-fluent-skin#2]
With the Background enabled certain elements of Bing's UI is not readable on certain searches where bing decides there should be blue in the title bar of shows or movies.
![Screen Shot 2023-05-17 at 12 24 26 PM](https://github.com/tobyisawesome/bing-fluent-skin/assets/96853437/c09433ee-046d-4943-80c7-2bda7e893470)
![Screen Shot 2023-05-17 at 12 26 15 PM](https://github.com/tobyisawesome/bing-fluent-skin/assets/96853437/6483b301-3b61-4952-ae94-d29084356902)

**Comment by tobyisawesome** [comment]
Fixed in latest update!

**Comment by smcmackin20** [comment]
Hello sorry to bother you but there is continued issues with the Ui but with the color green. Thank you so much for looking and fixing the UI thus far. The project looks amazing
![Screen Shot 2023-05-17 at 4 39 11 PM](https://github.com/tobyisawesome/bing-fluent-skin/assets/96853437/d58019bd-9d29-48f2-b3f9-8f6fe42cb48f)
