### ISSUE TITLE
"More" on Images Tab is Obfuscated

### ISSUE THREAD

**Issue by totallygeekdom** [tobyisawesome/bing-fluent-skin#5]
With skin:
![Screenshot 2023-07-15 214643](https://github.com/tobyisawesome/bing-fluent-skin/assets/76084843/08538a5d-c8e4-42a9-a216-28ad71e444e7)

Without skin:
![Screenshot 2023-07-15 215035](https://github.com/tobyisawesome/bing-fluent-skin/assets/76084843/7d8e0bf9-e5ec-45f0-aff6-309a37a810f7)

**Comment by tobyisawesome** [comment]
I think this is fixed now
