### ISSUE TITLE
Search Flyout Low Contrast/Wrong Color

### ISSUE THREAD

**Issue by totallygeekdom** [tobyisawesome/bing-fluent-skin#6]
With skin:
![Screenshot 2023-07-15 214711](https://github.com/tobyisawesome/bing-fluent-skin/assets/76084843/a04f1d86-2e55-4e6c-af0d-2f2cfbac8655)

Without skin:
![Screenshot 2023-07-15 215054](https://github.com/tobyisawesome/bing-fluent-skin/assets/76084843/c8c9edca-a3ec-4fa6-8d93-67d8c933abd2)

**Comment by tobyisawesome** [comment]
Should be good now.
